# Generated by Django 3.1.5 on 2021-01-17 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reward_Code',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField()),
                ('code', models.TextField()),
                ('max_times_redeemed', models.IntegerField()),
            ],
        ),
    ]
