# Generated by Django 3.1.5 on 2021-01-17 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0002_reward_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='uid',
            field=models.IntegerField(default='0'),
        ),
    ]
