# Generated by Django 3.1.2 on 2021-01-17 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0003_user_uid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='username',
            new_name='name',
        ),
    ]
