# Generated by Django 3.1.2 on 2021-01-17 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0005_auto_20210116_2039'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='name',
            field=models.TextField(default=''),
        ),
    ]
